### ISSUE TITLE
Creating object...and deserializeJson() failed: NoMemory

### ISSUE THREAD

**Issue by Crapy** [kristiantm/eink-family-calendar-esp32#3]
Getting this when running the calendar for the first time, any idea why?

**Comment by kristiantm** [comment]
Hmm. Have not seen it before. Two guesses
1) You have too many events in the calendar for the next 14 days (solution - try to limit the number of returns in the google script code)
2) The json library is too old a version. (Solution: Try adjusting the requirement in the platformio.ini file)

**Comment by Crapy** [comment]
> 

Thanks for your quick reply! I have limited it to 2 days to test as well as checked and I have the latest version of ArduinoJson
Issue still appears to exist, I have tried to change the board to esp32dev in platformio.ini which also didn't work

the json from openweather seems really huge could that be the issue?

EDIT: I have tested and removing the decode weather does appear to remove the error, although I don't see anything on the display (tested it with other demos and seems to work fine)

**Comment by kristiantm** [comment]
Ahh. The weather data seems to be missing from my own calendar, så perhaps I messed something up in the fix I did a few days ago.

My main change was to increase the timeout to 20 sec and to increase the version number of some of the libraries.

you could try to fetch the previous release and see if it fixes the problem.

**Comment by Crapy** [comment]
Doesn't seem to fix it, you say that you cannot see the weather in your calendar however I don't see anything at all in my e paper
any idea?

I use this e paper https://www.aliexpress.com/item/1005002311698459.html?spm=a2g0o.order_list.0.0.50f01802yXJbAR

with this esp32 https://www.aliexpress.com/item/32965291143.html?spm=a2g0o.order_list.0.0.50f01802yXJbAR

**Comment by kristiantm** [comment]
If you recieve the calendar events but it does not show, then it could be the connection to the eink display. Check that you have mapped the pins correctly and in case you have the black/white display instead of the tricolor, then make sure to uncomment.

I assume you have added all the relevant api’s to the wifi access point?

**Comment by Crapy** [comment]
> If you recieve the calendar events but it does not show, then it could be the connection to the eink display. Check that you have mapped the pins correctly and in case you have the black/white display instead of the tricolor, then make sure to uncomment.
> 
> I assume you have added all the relevant api’s to the wifi access point?

Yea, I can connect to the IP of the esp32 and configure the google script and etc, I also executed the google script and it appears to be fine, maybe because it's in hebrew it could cause an issue with the font?

**Comment by kristiantm** [comment]
Hmm - it could be. I have scandinavian letters in my calendar like æ, ø and å - however it just does not show these letters - but does show the rest.

Does it show the calendar events in the log when you connect via serial port and boot up?

**Comment by Crapy** [comment]
Yea it shows each event in a newline in putty

**Comment by Crapy** [comment]
Figured out the issue (maybe?), it says it cannot obtain time probably because the time is returned in hebrew in putty, need to figure out why
EDIT: unrelated still doesn't show anything on the display, maybe I need to change the board in platformio.ini or something?

I managed to get the weather working by changing onecall to weather but still doesn't show anything

I also get this error when compiling

`src/main.cpp: In function 'bool DecodeWeather(WiFiClient&, String)':
src/main.cpp:539:65: warning: 'typename ArduinoJson6194_F1::enable_if<ArduinoJson6194_F1::is_same<T, char*>::value, const char*>::type ArduinoJson6194_F1::MemberProxy<TParent, TStringRef>::as() const [with T = char*; TObject = ArduinoJson6194_F1::ElementProxy<ArduinoJson6194_F1::ArrayRef>; TStringRef = const char*; typename ArduinoJson6194_F1::enable_if<ArduinoJson6194_F1::is_same<T, char*>::value, const char*>::type = const char*]' is deprecated: Replace as<char*>() with as<const char*>() [-Wdeprecated-declarations]
       WxForecast[r].Dt                = list[r]["dt"].as<char*>();
                                                                 ^
In file included from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:9,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Document/BasicJsonDocument.hpp:7,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Document/DynamicJsonDocument.hpp:7,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson.hpp:28,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson.h:9,
                 from src/main.cpp:27:
.pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Object/MemberProxy.hpp:79:7: note: declared here
       as() const {
       ^~
src/main.cpp:545:81: warning: 'typename ArduinoJson6194_F1::enable_if<ArduinoJson6194_F1::is_same<T, char*>::value, const char*>::type ArduinoJson6194_F1::MemberProxy<TParent, TStringRef>::as() const [with T = char*; TObject = ArduinoJson6194_F1::ElementProxy<ArduinoJson6194_F1::MemberProxy<ArduinoJson6194_F1::ElementProxy<ArduinoJson6194_F1::ArrayRef>, const char*> >; TStringRef = const char*; typename ArduinoJson6194_F1::enable_if<ArduinoJson6194_F1::is_same<T, char*>::value, const char*>::type = const char*]' is deprecated: Replace as<char*>() with as<const char*>() [-Wdeprecated-declarations]
       WxForecast[r].Icon              = list[r]["weather"][0]["icon"].as<char*>();       // Serial.println("Icon: "+String(WxForecast[r].Icon));
                                                                                 ^
In file included from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:9,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Document/BasicJsonDocument.hpp:7,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Document/DynamicJsonDocument.hpp:7,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson.hpp:28,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson.h:9,
                 from src/main.cpp:27:
.pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Object/MemberProxy.hpp:79:7: note: declared here
       as() const {
       ^~
src/main.cpp:546:88: warning: 'typename ArduinoJson6194_F1::enable_if<ArduinoJson6194_F1::is_same<T, char*>::value, const char*>::type ArduinoJson6194_F1::MemberProxy<TParent, TStringRef>::as() const [with T = char*; TObject = ArduinoJson6194_F1::ElementProxy<ArduinoJson6194_F1::MemberProxy<ArduinoJson6194_F1::ElementProxy<ArduinoJson6194_F1::ArrayRef>, const char*> >; TStringRef = const char*; typename ArduinoJson6194_F1::enable_if<ArduinoJson6194_F1::is_same<T, char*>::value, const char*>::type = const char*]' is deprecated: Replace as<char*>() with as<const char*>() [-Wdeprecated-declarations]
       WxForecast[r].Description       = list[r]["weather"][0]["description"].as<char*>(); Serial.println("Desc: "+String(WxForecast[r].Description));
                                                                                        ^
In file included from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:9,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Document/BasicJsonDocument.hpp:7,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Document/DynamicJsonDocument.hpp:7,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson.hpp:28,
                 from .pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson.h:9,
                 from src/main.cpp:27:
.pio/libdeps/lolin32/ArduinoJson/src/ArduinoJson/Object/MemberProxy.hpp:79:7: note: declared here
       as() const {
       ^~`

**Comment by Crapy** [comment]
Managed to fix it by changing the display to the correct one 
`GxEPD2_3C<GxEPD2_750c, GxEPD2_750c::HEIGHT/2> display(GxEPD2_750c(/*CS=*/ 15, /*DC=*/ 27, /*RST=*/ 26, /*BUSY=*/ 25));`

**Comment by kristiantm** [comment]
Happy to hear that it works :)
