### ISSUE TITLE
Not an issue - sorry, just wanted to get in touch!

### ISSUE THREAD

**Issue by O491dogan** [kristiantm/eink-family-calendar-esp32#5]
Hi Kristian, 
you can mark this as closed because it's not an issue at all. I just wanted to get in touch with you because I really like your project!
I haven't built it yet because I wonder, how and if it would be possible to connect to calendars using caldav. I'm hosting a nextcloud instance with all my calendars.

There are a lot of solutions on the internet, but most of them use a pi... due to the fact that I don't want to use a power outlet because of the ugly cable, I really like your approach with the ESP. Also the pi consumes way more power than the µc.
I've already tried to find some suitable libraries online but didn't come up with something useful. As you might have some experience with all this stuff I'd like to ask, if you've thought about connecting via caldav and maybe have some ideas.

Thank you and thank you for sharing your project!

**Comment by kristiantm** [comment]
You are welcome. Had a lot of fun making it - and am enjoying it every morning at the wall 🙂

For accessing caldav via esp32 - it should be possible as it seems that you just connect with a normal web-client - like the one I am using in my project. 

However - I would recommend to limit the amount of returndata - I assume you can request a range of dates or similar. This is why I did not just do an ical integration in my project as it tries to synchronize the entire calendar.
