### ISSUE TITLE
Connecting a fuel gauge to the waveshare?

### ISSUE THREAD

**Issue by Crapy** [kristiantm/eink-family-calendar-esp32#6]
Hi, so I ran the project and it works fine, but to get accurate reading about the battery level I connected the battery to a max17043 and connected that to the waveshare, I was wondering if there is anyway to connect the SDA and SCL connectors from the max17043 to waveshare esp32 to view the data? Have you engaged in anything like that?

**Comment by kristiantm** [comment]
Hi. Happy that you like the project.

I have not done so myself but can see that the esp32 boards should be perfectly capable of doing so. Try the link below and let me know if you get it to work. Could be a nice addition to the project.

https://randomnerdtutorials.com/esp32-i2c-communication-arduino-ide/

**Comment by Crapy** [comment]
> Hi. Happy that you like the project.
> 
> I have not done so myself but can see that the esp32 boards should be perfectly capable of doing so. Try the link below and let me know if you get it to work. Could be a nice addition to the project.
> 
> https://randomnerdtutorials.com/esp32-i2c-communication-arduino-ide/

Yea with other boards it's easy enough but I can't find any proper schematics on the waveshare board which is the one I got, I am trying to do it all under it. I have already connected the fuel gauge and used a tp4056 so it can be recharged, now I need to connect the SCL and SDA to recieve the data and present it on the screen but I cannot for the life of me figure out where to cnnect it on that board, the SCK and the SD0,SD1,SD2 are used by the SPI interface

**Comment by kristiantm** [comment]
The schematics are here:
https://www.waveshare.com/w/upload/8/80/E-Paper_ESP32_Driver_Board_Schematic.pdf

The clock is at pin 19 (as per schematic) and think you can use any analogue pin as SDA (as per the other link). Be aware that some are in use to drive the screen - check my code for the pin initialization line.

**Comment by kristiantm** [comment]
Hmm - or perhaps experiment with setting another IO that is nor in use as the clock.

![0E9E1595-89BA-4B65-ABDF-E9AE6E665176](https://user-images.githubusercontent.com/61930466/205847286-894e81fa-4c09-4d58-8fa6-3b755a3603f9.png)

**Comment by Crapy** [comment]
Well I've tried using the 21 and 22 pins but I'm not getting any data from it

**Comment by Crapy** [comment]
Managed to fix it by replacing the fuel gauge with a new one
